#!/bin/bash

PID_FILE=/vagrant/speech/synthesis/server/server.pid
LOG_FILE=/vagrant/speech/synthesis/server/server.log

start() {
	if [ ! -f $PID_FILE ]; then
		cd /vagrant/speech/synthesis/server
		nohup ./server.py > $LOG_FILE 2>&1&
		echo $! > $PID_FILE
	fi 
}

stop() {
	if [ -f $PID_FILE ]; then
		sudo kill -9 `cat $PID_FILE`
		rm $PID_FILE
	fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: synthesis {start|stop|restart}"
        exit 1
        ;;
esac
exit 0